version: '3.1'

services:

  publication-db:
    image: mongo:latest
    container_name: authentication-db
    restart: always
    networks:
      - circuit-breaker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27018:27017

  redis-compose:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - "6379:6379"

networks:
  circuit-breaker:
    driver: bridge