spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017/admin}
      database: admin
server:
  port: 3005

client:
  comments:
    url: http://localhost:8083

resilience4j.circuitbreaker:
  instances:
    comments:
      slidingWindowSize: 8
      minimumNumberOfCalls: 4
#      permittedNumberOfCallsInHalfOpenState: 2
#      waitDurationInOpenState: 10000
#      slowCallDurationThreshold: 500
#      slowCallRateThreshold: 20